### Data Exploration and Preprocessing

In [1]:
'''
Load the review and metadata files from data/raw for the Electronics Category and comlete EDA on a sample since review size is 18.7M rows.
Used Polars for initial reading in as the file contains 18.3M rows 
Dataset from: https://amazon-reviews-2023.github.io
'''
import polars as pl
import pickle
from pathlib import Path

In [2]:
DATA_DIR = Path("../data/raw")

# use scan_ndjson in polars so we do not load all data immediately into memory -> avoids OOM errors: https://docs.pola.rs/user-guide/io/json/#write
reviews = pl.scan_ndjson(DATA_DIR / "Electronics.jsonl")
product_metadata = pl.scan_ndjson(DATA_DIR / "meta_Electronics.jsonl", schema_overrides = {"price": pl.Utf8}) # Schema parsing happens before transformations in Polars so we Polars tries to read schema and parse float64 right away, so we have to override the schema so Polars treats price as a string before transforming it

# execute the lazy query plan that is currently stored to see example rows for product reviews
print("Example rows from Product Reviews dataframe: ")
reviews.head().collect()

Example rows from Product Reviews dataframe:

shape: (5, 10)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ rating ┆ title      ┆ text       ┆ images    ┆ … ┆ user_id   ┆ timestamp ┆ helpful_v ┆ verified_ │
│ ---    ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ote       ┆ purchase  │
│ f64    ┆ str        ┆ str        ┆ list[stru ┆   ┆ str       ┆ i64       ┆ ---       ┆ ---       │
│        ┆            ┆            ┆ ct[4]]    ┆   ┆           ┆           ┆ i64       ┆ bool      │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3.0    ┆ Smells     ┆ First &    ┆ [{"https: ┆ … ┆ AFKZENTNB ┆ 165818511 ┆ 0         ┆ true      │
│        ┆ like       ┆ most       ┆ //m.media ┆   ┆ Q7A7V7UXW ┆ 7948      ┆           ┆           │
│        ┆ gasoline!  ┆ offensive: ┆ -amazon.c ┆   ┆ 5JJI6UGRY ┆           ┆           ┆           │
│        ┆ Going ba…  ┆ they r…    ┆ om/…      ┆   ┆ Q         ┆           ┆           ┆           │
│ 1.0    ┆ Didn’t     ┆ These      ┆ []        ┆ … ┆ AFKZENTNB ┆ 159267854 ┆ 0         ┆ true      │
│        ┆ work at    ┆ didn’t     ┆           ┆   ┆ Q7A7V7UXW ┆ 9731      ┆           ┆           │
│        ┆ all lenses ┆ work. Idk  ┆           ┆   ┆ 5JJI6UGRY ┆           ┆           ┆           │
│        ┆ loos…      ┆ if they…   ┆           ┆   ┆ Q         ┆           ┆           ┆           │
│ 5.0    ┆ Excellent! ┆ I love     ┆ []        ┆ … ┆ AFKZENTNB ┆ 152309301 ┆ 0         ┆ true      │
│        ┆            ┆ these.     ┆           ┆   ┆ Q7A7V7UXW ┆ 7534      ┆           ┆           │
│        ┆            ┆ They even  ┆           ┆   ┆ 5JJI6UGRY ┆           ┆           ┆           │
│        ┆            ┆ come w…    ┆           ┆   ┆ Q         ┆           ┆           ┆           │
│ 5.0    ┆ Great      ┆ I was      ┆ []        ┆ … ┆ AGGZ357AO ┆ 129027849 ┆ 18        ┆ true      │
│        ┆ laptop     ┆ searching  ┆           ┆   ┆ 26RQZVRLG ┆ 5000      ┆           ┆           │
│        ┆ backpack!  ┆ for a      ┆           ┆   ┆ U4D4N52DZ ┆           ┆           ┆           │
│        ┆            ┆ sturdy b…  ┆           ┆   ┆ Q         ┆           ┆           ┆           │
│ 5.0    ┆ Best       ┆ I've       ┆ []        ┆ … ┆ AG2L7H23R ┆ 167660158 ┆ 0         ┆ true      │
│        ┆ Headphones ┆ bought     ┆           ┆   ┆ 5LLKDKLBE ┆ 1238      ┆           ┆           │
│        ┆ in the     ┆ these      ┆           ┆   ┆ F2Q3L2MVD ┆           ┆           ┆           │
│        ┆ Fifties…   ┆ headphones ┆           ┆   ┆ A         ┆           ┆           ┆           │
│        ┆            ┆ t…         ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
# print example rows from product metadata
print("Example rows from Product metadata dataframe: ")
product_metadata.head().collect()

Example rows from Product metadata dataframe:

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ main_cate ┆ title     ┆ average_r ┆ rating_nu ┆ … ┆ categorie ┆ details   ┆ parent_as ┆ bought_t │
│ gory      ┆ ---       ┆ ating     ┆ mber      ┆   ┆ s         ┆ ---       ┆ in        ┆ ogether  │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ struct[16 ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ i64       ┆   ┆ list[str] ┆ 5]        ┆ str       ┆ null     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ All Elect ┆ FS-1051   ┆ 3.5       ┆ 6         ┆ … ┆ ["Electro ┆ {null,nul ┆ B00MCW7G9 ┆ null     │
│ ronics    ┆ FATSHARK  ┆           ┆           ┆   ┆ nics",    ┆ l,null,nu ┆ M         ┆          │
│           ┆ TELEPORTE ┆           ┆           ┆   ┆ "Televisi ┆ ll,null,n ┆           ┆          │
│           ┆ R V3…     ┆           ┆           ┆   ┆ on & …    ┆ ull…      ┆           ┆          │
│ All Elect ┆ Ce-H22B12 ┆ 5.0       ┆ 1         ┆ … ┆ ["Electro ┆ {null,nul ┆ B00YT6XQS ┆ null     │
│ ronics    ┆ -S1 4Kx2K ┆           ┆           ┆   ┆ nics",    ┆ l,null,nu ┆ E         ┆          │
│           ┆ Hdmi      ┆           ┆           ┆   ┆ "Televisi ┆ ll,null,n ┆           ┆          │
│           ┆ 4Port     ┆           ┆           ┆   ┆ on & …    ┆ ull…      ┆           ┆          │
│ Computers ┆ Digi-Tato ┆ 4.5       ┆ 246       ┆ … ┆ ["Electro ┆ {"Digi-Ta ┆ B07SM135L ┆ null     │
│           ┆ o Decal   ┆           ┆           ┆   ┆ nics",    ┆ too","Fre ┆ S         ┆          │
│           ┆ Skin      ┆           ┆           ┆   ┆ "Computer ┆ sh Marble ┆           ┆          │
│           ┆ Compatib… ┆           ┆           ┆   ┆ s & A…    ┆ ","…      ┆           ┆          │
│ AMAZON    ┆ NotoCity  ┆ 4.5       ┆ 233       ┆ … ┆ ["Electro ┆ {null,nul ┆ B089CNGZC ┆ null     │
│ FASHION   ┆ Compatibl ┆           ┆           ┆   ┆ nics",    ┆ l,null,nu ┆ W         ┆          │
│           ┆ e with    ┆           ┆           ┆   ┆ "Wearable ┆ ll,null,n ┆           ┆          │
│           ┆ Vivoa…    ┆           ┆           ┆   ┆ Tech…     ┆ ull…      ┆           ┆          │
│ Cell      ┆ Motorola  ┆ 3.8       ┆ 64        ┆ … ┆ ["Electro ┆ {null,nul ┆ B004E2Z88 ┆ null     │
│ Phones &  ┆ Droid X   ┆           ┆           ┆   ┆ nics",    ┆ l,null,nu ┆ O         ┆          │
│ Accessori ┆ Essential ┆           ┆           ┆   ┆ "Computer ┆ ll,null,n ┆           ┆          │
│ es        ┆ s Co…     ┆           ┆           ┆   ┆ s & A…    ┆ ull…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
'''
Overview of the dataset: Column names/fields, types, size of each dataset, Example records
'''
print(f"Reviews colums: {reviews.collect_schema().names()}\n")
print(f"Reviews colum types: {reviews.collect_schema().dtypes}\n\n")

print(f"Metadata colums: {product_metadata.collect_schema().names()}")
print(f"Metadata colums: {product_metadata.collect_schema().dtypes}")

# fetch number of rows and columns in the reviews and metadata datasets
num_review_rows = reviews.select(pl.len()).collect().item()
num_review_cols = len(reviews.columns)

num_metadata_rows = product_metadata.select(pl.len()).collect().item()
num_metadata_cols = len(product_metadata.columns)

print(f"Reviews row count: {num_review_rows}, shape: ({num_review_rows, num_review_cols})")
print(f"Metadata row count: {num_metadata_rows}, shape: ({num_metadata_rows, num_metadata_cols})")

print("Example records of Reviews Dataset: ")
print(reviews.fetch(5))

print("Example records of Product Metadata Dataset: ")
product_metadata.fetch(5)

Reviews colums: ['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase']

Reviews colum types: <bound method Schema.dtypes of Schema({'rating': Float64, 'title': String, 'text': String, 'images': List(Struct({'small_image_url': String, 'medium_image_url': String, 'large_image_url': String, 'attachment_type': String})), 'asin': String, 'parent_asin': String, 'user_id': String, 'timestamp': Int64, 'helpful_vote': Int64, 'verified_purchase': Boolean})>


Metadata colums: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together']
Metadata colums: <bound method Schema.dtypes of Schema({'main_category': String, 'title': String, 'average_rating': Float64, 'rating_number': Int64, 'features': List(String), 'description': List(String), 'price': String, 'images': List(Struct({'thumb': String, 'large': String, 'variant': String, 'hi_res': String})), 'videos': List(Struct({'title': String, 'url': String, 'user_id': String})), 'store': String, 'categories': List(String), 'details': Struct({'Brand': String, 'Color': String, 'Room Type': String, 'Material': String, 'Theme': String, 'Style': String, 'Age Range (Description)': String, 'Reusability': String, 'Pattern': String, 'Shape': String, 'Unit Count': String, 'Finish Type': String, 'Item Weight': String, 'Package Dimensions': String, 'Manufacturer': String, 'Country of Origin': String, 'Date First Available': String, 'Best Sellers Rank': Struct({'Electronics': Int64, 'Smart Arm & Wristband Accessories': Int64, 'Computers & Accessories': Int64, 'Laptop Decals': Int64, 'Fish Finders & Depth Finders': Int64, 'Computer Network Adapters': Int64, 'Data Storage': Int64, 'Computer Speakers': Int64, 'Traditional Laptop Computers': Int64, 'Mirrorless Camera Lenses': Int64, 'Film Cameras': Int64, 'Audio & Video Turntables': Int64, 'Amazon Renewed': Int64, 'Computer Graphics Cards': Int64, 'Computer Keyboards': Int64, 'Car Audio & Video Antennas': Int64, 'Computer Monitors': Int64, 'Laptop Hard Shell Cases': Int64, 'Tablet Cases': Int64, 'Surveillance Housing & Mounting Brackets': Int64, 'SecureDigital Memory Cards': Int64, 'Computer Networking': Int64, 'Speaker Cables': Int64, 'Micro SD Memory Cards': Int64, 'Laptop Docking Stations': Int64, 'Laptop Skins': Int64, 'Portable Bluetooth Speakers': Int64, 'Climate Pledge Friendly: Electronics': Int64, 'Headphone Earpads': Int64, 'Car Audio & Video Installation Products': Int64, 'Floor Cord Covers': Int64, 'Portable FRS Two-Way Radios': Int64, 'Earbud & In-Ear Headphones': Int64, 'Headphone Cases': Int64, 'Home Audio Sound Bars': Int64, 'Desktop Computer Fan Grills': Int64, 'Telescope Motor Drives': Int64, 'Cable Straps': Int64, 'eBook Reader Covers': Int64, 'Computer Cables & Interconnects': Int64, 'DVI-HDMI Adapters': Int64, 'USB Cables': Int64, 'Photographic Studio Photo Backgrounds': Int64, 'Computer Networking Wireless Access Points': Int64}), 'Product Dimensions': String, 'Item model number': String, 'Is Discontinued By Manufacturer': String, 'Other display features': String, 'Item Package Dimensions L x W x H': String, 'Package Weight': String, 'Item Dimensions  LxWxH': String, 'Brand Name': String, 'Suggested Users': String, 'Number of Items': String, 'Part Number': String, 'Model Year': String, 'Special features': String, 'Light Source Type': String, 'Magnification Maximum': String, 'Compatible Devices': String, 'Objective Lens Description': String, 'Power Source': String, 'Compatible Phone Models': String, 'Item Dimensions LxWxH': String, 'Hardware Platform': String, 'Operating System': String, 'Language': String, 'Format': String, 'Publication Date': String, 'Model number': String, 'Standing screen display size': String, 'Form Factor': String, 'Memory Storage Capacity': String, 'Hardware Interface': String, 'Connectivity Technology': String, 'Model Name': String, 'Speaker Type': String, 'Special Feature': String, 'Number of Channels': String, 'Media Format Digital Video': String, 'Hard Drive': String, 'Flash Memory Size': String, 'Hard Drive Interface': String, 'Digital Storage Capacity': String, 'Hard Disk Interface': String, 'Hard Disk Form Factor': String, 'Hard Disk Description': String, 'Hard Disk Size': String, 'Specific Uses For Product': String, 'Series': String, 'Hard Drive Rotational Speed': String, 'Hard Disk Rotational Speed': String, 'Surface Recommendation': String, 'Number of Pieces': String, 'Installation Type': String, 'Max Screen Resolution': String, 'Processor': String, 'RAM': String, 'Memory Speed': String, 'Graphics Coprocessor': String, 'Chipset Brand': String, 'Card Description': String, 'Graphics Card Ram Size': String, 'Number of USB 3.0 Ports': String, 'Processor Brand': String, 'Number of Processors': String, 'Computer Memory Type': String, 'Optical Drive Type': String, 'Screen Size': String, 'CPU Model': String, 'Ram Memory Installed Size': String, 'Lens Type': String, 'Compatible Mountings': String, 'Camera Lens Description': String, 'Maximum Focal Length': String, 'Subwoofer Diameter': String, 'Mounting Type': String, 'Surround Sound Channel Configuration': String, 'Is Waterproof': String, 'Film Format Type': String, 'Film Color': String, 'Exposure Control Type': String, 'Motor Type': String, 'Signal Format': String, 'Graphics Ram Size': String, 'Video Output Interface': String, 'Graphics Processor Manufacturer': String, 'Number of Keys': String, 'Switch Type': String, 'Antenna': String, 'Resolution': String, 'Display Technology': String, 'Orientation': String, 'Vehicle Service Type': String, 'Video Capture Resolution': String, 'Control Method': String, 'Size': String, 'Shell Type': String, 'Manufacturer Part Number': String, 'Display Size': String, 'Voice command': String, 'Human Interface Input': String, 'Are Batteries Included': String, 'Connector Type': String, 'Number of Ports': String, 'Item Package Quantity': String, 'Flash Memory Type': String, 'Handle Material': String, 'Grip Type': String, 'Connector Gender': String, 'Gauge': String, 'Batteries': String, 'Total USB Ports': String, 'Total HDMI Ports': String, 'Wattage': String, 'Power Connector Type': String, 'Voltage': String, 'Cooling Method': String, 'Maximum Rotational Speed': String, 'Batteries Required?': String, 'Screen Resolution': String, 'Wireless Type': String, 'Graphics Card Description': String, 'Display Type': String, 'Warranty': String, 'Frequency Range': String, 'Tuner Technology': String, 'Water Resistance Level': String, 'Wireless Communication Technology': String, 'Batteries Included?': String, 'Cable Type': String, 'Data Transfer Rate': String, 'Whats in the box': String, 'Controller Type': String, 'Recommended Uses For Product': String, 'Department': String, 'CPU Speed': String, 'Rear Webcam Resolution': String, 'Number of USB 2.0 Ports': String, 'Average Battery Life (in hours)': String, 'Minimum Focal Length': String, 'Output Voltage': String, 'Current Rating': String, 'Main Power Connector Type': String, 'Occasion': String, 'Product Care Instructions': String, 'Closure Type': String, 'Wheel Type': String, 'Outer Material': String, 'Age Range Description': String, 'Cache Size': String}), 'parent_asin': String, 'bought_together': Null})>

/var/folders/ks/6zk2yh691g72m6mndxtp0bx40000gn/T/ipykernel_55364/2550683999.py:12: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  num_review_cols = len(reviews.columns)

Reviews row count: 43886944, shape: ((43886944, 10))
Metadata row count: 1610012, shape: ((1610012, 14))
Example records of Reviews Dataset:
shape: (5, 10)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ rating ┆ title      ┆ text       ┆ images    ┆ … ┆ user_id   ┆ timestamp ┆ helpful_v ┆ verified_ │
│ ---    ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ote       ┆ purchase  │
│ f64    ┆ str        ┆ str        ┆ list[stru ┆   ┆ str       ┆ i64       ┆ ---       ┆ ---       │
│        ┆            ┆            ┆ ct[4]]    ┆   ┆           ┆           ┆ i64       ┆ bool      │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3.0    ┆ Smells     ┆ First &    ┆ [{"https: ┆ … ┆ AFKZENTNB ┆ 165818511 ┆ 0         ┆ true      │
│        ┆ like       ┆ most       ┆ //m.media ┆   ┆ Q7A7V7UXW ┆ 7948      ┆           ┆           │
│        ┆ gasoline!  ┆ offensive: ┆ -amazon.c ┆   ┆ 5JJI6UGRY ┆           ┆           ┆           │
│        ┆ Going ba…  ┆ they r…    ┆ om/…      ┆   ┆ Q         ┆           ┆           ┆           │
│ 1.0    ┆ Didn’t     ┆ These      ┆ []        ┆ … ┆ AFKZENTNB ┆ 159267854 ┆ 0         ┆ true      │
│        ┆ work at    ┆ didn’t     ┆           ┆   ┆ Q7A7V7UXW ┆ 9731      ┆           ┆           │
│        ┆ all lenses ┆ work. Idk  ┆           ┆   ┆ 5JJI6UGRY ┆           ┆           ┆           │
│        ┆ loos…      ┆ if they…   ┆           ┆   ┆ Q         ┆           ┆           ┆           │
│ 5.0    ┆ Excellent! ┆ I love     ┆ []        ┆ … ┆ AFKZENTNB ┆ 152309301 ┆ 0         ┆ true      │
│        ┆            ┆ these.     ┆           ┆   ┆ Q7A7V7UXW ┆ 7534      ┆           ┆           │
│        ┆            ┆ They even  ┆           ┆   ┆ 5JJI6UGRY ┆           ┆           ┆           │
│        ┆            ┆ come w…    ┆           ┆   ┆ Q         ┆           ┆           ┆           │
│ 5.0    ┆ Great      ┆ I was      ┆ []        ┆ … ┆ AGGZ357AO ┆ 129027849 ┆ 18        ┆ true      │
│        ┆ laptop     ┆ searching  ┆           ┆   ┆ 26RQZVRLG ┆ 5000      ┆           ┆           │
│        ┆ backpack!  ┆ for a      ┆           ┆   ┆ U4D4N52DZ ┆           ┆           ┆           │
│        ┆            ┆ sturdy b…  ┆           ┆   ┆ Q         ┆           ┆           ┆           │
│ 5.0    ┆ Best       ┆ I've       ┆ []        ┆ … ┆ AG2L7H23R ┆ 167660158 ┆ 0         ┆ true      │
│        ┆ Headphones ┆ bought     ┆           ┆   ┆ 5LLKDKLBE ┆ 1238      ┆           ┆           │
│        ┆ in the     ┆ these      ┆           ┆   ┆ F2Q3L2MVD ┆           ┆           ┆           │
│        ┆ Fifties…   ┆ headphones ┆           ┆   ┆ A         ┆           ┆           ┆           │
│        ┆            ┆ t…         ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Example records of Product Metadata Dataset:

/var/folders/ks/6zk2yh691g72m6mndxtp0bx40000gn/T/ipykernel_55364/2550683999.py:15: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  num_metadata_cols = len(product_metadata.columns)
/var/folders/ks/6zk2yh691g72m6mndxtp0bx40000gn/T/ipykernel_55364/2550683999.py:21: DeprecationWarning: `LazyFrame.fetch` is deprecated; use `LazyFrame.collect` instead, in conjunction with a call to `head`.
  print(reviews.fetch(5))
/var/folders/ks/6zk2yh691g72m6mndxtp0bx40000gn/T/ipykernel_55364/2550683999.py:24: DeprecationWarning: `LazyFrame.fetch` is deprecated; use `LazyFrame.collect` instead, in conjunction with a call to `head`.
  product_metadata.fetch(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ main_cate ┆ title     ┆ average_r ┆ rating_nu ┆ … ┆ categorie ┆ details   ┆ parent_as ┆ bought_t │
│ gory      ┆ ---       ┆ ating     ┆ mber      ┆   ┆ s         ┆ ---       ┆ in        ┆ ogether  │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ struct[16 ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ i64       ┆   ┆ list[str] ┆ 5]        ┆ str       ┆ null     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ All Elect ┆ FS-1051   ┆ 3.5       ┆ 6         ┆ … ┆ ["Electro ┆ {null,nul ┆ B00MCW7G9 ┆ null     │
│ ronics    ┆ FATSHARK  ┆           ┆           ┆   ┆ nics",    ┆ l,null,nu ┆ M         ┆          │
│           ┆ TELEPORTE ┆           ┆           ┆   ┆ "Televisi ┆ ll,null,n ┆           ┆          │
│           ┆ R V3…     ┆           ┆           ┆   ┆ on & …    ┆ ull…      ┆           ┆          │
│ All Elect ┆ Ce-H22B12 ┆ 5.0       ┆ 1         ┆ … ┆ ["Electro ┆ {null,nul ┆ B00YT6XQS ┆ null     │
│ ronics    ┆ -S1 4Kx2K ┆           ┆           ┆   ┆ nics",    ┆ l,null,nu ┆ E         ┆          │
│           ┆ Hdmi      ┆           ┆           ┆   ┆ "Televisi ┆ ll,null,n ┆           ┆          │
│           ┆ 4Port     ┆           ┆           ┆   ┆ on & …    ┆ ull…      ┆           ┆          │
│ Computers ┆ Digi-Tato ┆ 4.5       ┆ 246       ┆ … ┆ ["Electro ┆ {"Digi-Ta ┆ B07SM135L ┆ null     │
│           ┆ o Decal   ┆           ┆           ┆   ┆ nics",    ┆ too","Fre ┆ S         ┆          │
│           ┆ Skin      ┆           ┆           ┆   ┆ "Computer ┆ sh Marble ┆           ┆          │
│           ┆ Compatib… ┆           ┆           ┆   ┆ s & A…    ┆ ","…      ┆           ┆          │
│ AMAZON    ┆ NotoCity  ┆ 4.5       ┆ 233       ┆ … ┆ ["Electro ┆ {null,nul ┆ B089CNGZC ┆ null     │
│ FASHION   ┆ Compatibl ┆           ┆           ┆   ┆ nics",    ┆ l,null,nu ┆ W         ┆          │
│           ┆ e with    ┆           ┆           ┆   ┆ "Wearable ┆ ll,null,n ┆           ┆          │
│           ┆ Vivoa…    ┆           ┆           ┆   ┆ Tech…     ┆ ull…      ┆           ┆          │
│ Cell      ┆ Motorola  ┆ 3.8       ┆ 64        ┆ … ┆ ["Electro ┆ {null,nul ┆ B004E2Z88 ┆ null     │
│ Phones &  ┆ Droid X   ┆           ┆           ┆   ┆ nics",    ┆ l,null,nu ┆ O         ┆          │
│ Accessori ┆ Essential ┆           ┆           ┆   ┆ "Computer ┆ ll,null,n ┆           ┆          │
│ es        ┆ s Co…     ┆           ┆           ┆   ┆ s & A…    ┆ ull…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

#### Selection and Justification of Fields for Retrieval

##### Reviews: 

We keep the rating, title, and parent_asin columns in the Reviews dataset. 

The text field was left out since it contains the full user review of the product, which would be very large and expensive to embed for each product. The title column provides a better overview of the review itself without containing the full text so that the review sentiment of products can be retrieved along with the product so users can query for products with a specific critertia such as "great battery life" for example

The title column is more useful since it gives a semantic summary of the full review and can add extra inmportant context that the user can retrieve for. For example, the title column lets users query for short phrases such as "long lasting" and retrieve relevant reviews since the title summarizes the main idea of the product review. 

The rating column is helpful for sentiment analysis and metadata later on. so we can later return results based on the how positive or negative a review is. 

parent_asin is kept since it lets us join the Reviews table with the Metadata table on a common key, so every product review can be linked back to its specific product metadata.  

We dropped columns like text, images, asin, timestamp, and user_id since they do not add value for text-based retrieval systems without adding ambiguity. helpful_vote and verified_purchase were also not included to keep the information stored in embeddings more focused on the semantics of the review itself. 

##### Product Metadata: 

We keep the main_category, title, average_rating, rating_number, features, description, price, store, categories, and parent_asin columns. 

The title, description, features and categories fields are the most important for retrieval since since they contain the main description about the product like what the product is, what it does, and how it is categorized.

main_category and store fields were also kept to provide extra context about the product such as what store holds it and specific details such as the material of the prodict. The average_rating and rating_number are useful as metadata so the user can query products based on popularity or quality. The price field is also included to support queries that contain price range filters.

parent_asin is kept again as a joining key so that we can link the metadata table to each products' review. 

We removed images, videos, bought_together, and details since they are not that useful for direct text based retrieval only and do not provide much extra context unless we want to do something like content recommendation.

In [5]:
reviews = reviews.select([
    "parent_asin",
    "rating",
    "title"
])

product_metadata = product_metadata.select([
    "parent_asin",
    "main_category",
    "title",
    "average_rating",
    "rating_number",
    "features",
    "description",
    "price",
    "store",
    "categories"
])

#### Text Preprocessing Decisions

We keep preprocessing simple and focus on keeping the original meaning of the product and review text.

For both the reviews and metadata datasets, we lowercase the text, handle null values, and remove extra whitespace. These steps make the text more consistent without removing important meaning. For example, lowercasing ensures that words such as “Battery” and “battery” are treated the same during retrieval, while whitespace normalization helps clean up irregular spacing from raw text fields. We also chose to join the reviews and metadata datasets on the parent_asin key before building the retrieval corpus. This is because every review and product metadata document is stored in different tables so joining them lets every retrieval document contain the product metadata context like the title, description and features, along with the review level context like the review title and review text. This makes the retrieval for the end user more robust as it makes it easier to retrieve both product descriptions and user reviews to user queries. 

For the metadata dataset, some columns such as features, description, categories, and details contain lists of strings. We plan to convert these fields into text strings so they can be included in the retrieval text more cleanly instead of being stored as list data structures.

In [6]:
# preprocess the review field by lowercasing the next, handling null values, and removing extra whitespace 
reviews_clean = reviews.with_columns([
    pl.col("title")
        .fill_null("")
        .str.to_lowercase()
        .str.replace_all(r"\s+", " ") # replace 1+ whitespace chars
        .str.strip_chars()
        .alias("review_title"),
])


# preprocess the metadata fields with the same preprocessing: fill in null values, lowercase them, and replace whitespace chars
product_metadata_clean = product_metadata.with_columns([
    pl.col("main_category")
      .fill_null("")
      .str.to_lowercase()
      .str.replace_all(r"\s+", " ")
      .str.strip_chars(),

    pl.col("title")
      .fill_null("")
      .str.to_lowercase()
      .str.replace_all(r"\s+", " ")
      .str.strip_chars()
      .alias("product_title"),

    pl.col("store")
      .fill_null("")
      .str.to_lowercase()
      .str.replace_all(r"\s+", " ")
      .str.strip_chars(),

    # convert list/string fields to string format
    pl.col("features")
      .list.join(" ")
      .fill_null("")
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.replace_all(r"\s+", " ")
      .str.strip_chars(),

    pl.col("description")
      .list.join(" ")
      .fill_null("")
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.replace_all(r"\s+", " ")
      .str.strip_chars(),

    pl.col("categories")
      .list.join(" ")
      .fill_null("")
      .cast(pl.Utf8)
      .str.to_lowercase()
      .str.replace_all(r"\s+", " ")
      .str.strip_chars(), 

    pl.col("price")
      .cast(pl.Utf8, strict = False)
      .fill_null("")
      .str.to_lowercase()
      .str.replace_all(r"\s+", " ")
      .str.strip_chars()
])

In [7]:
print("Example records of Cleaned Review Dataset: ")
print(reviews_clean.head().collect())

Example records of Cleaned Review Dataset:
shape: (5, 4)
┌─────────────┬────────┬─────────────────────────────────┬─────────────────────────────────┐
│ parent_asin ┆ rating ┆ title                           ┆ review_title                    │
│ ---         ┆ ---    ┆ ---                             ┆ ---                             │
│ str         ┆ f64    ┆ str                             ┆ str                             │
╞═════════════╪════════╪═════════════════════════════════╪═════════════════════════════════╡
│ B083NRGZMM  ┆ 3.0    ┆ Smells like gasoline! Going ba… ┆ smells like gasoline! going ba… │
│ B07N69T6TM  ┆ 1.0    ┆ Didn’t work at all lenses loos… ┆ didn’t work at all lenses loos… │
│ B01G8JO5F2  ┆ 5.0    ┆ Excellent!                      ┆ excellent!                      │
│ B001OC5JKY  ┆ 5.0    ┆ Great laptop backpack!          ┆ great laptop backpack!          │
│ B07CJYMRWM  ┆ 5.0    ┆ Best Headphones in the Fifties… ┆ best headphones in the fifties… │
└─────────────┴────────┴─────────────────────────────────┴─────────────────────────────────┘

In [8]:
print("Example records of Cleaned Product Metadata Dataset: ")
print(product_metadata_clean.head().collect())

Example records of Cleaned Product Metadata Dataset:
shape: (5, 11)
┌────────────┬────────────┬────────────┬───────────┬───┬───────┬───────────┬───────────┬───────────┐
│ parent_asi ┆ main_categ ┆ title      ┆ average_r ┆ … ┆ price ┆ store     ┆ categorie ┆ product_t │
│ n          ┆ ory        ┆ ---        ┆ ating     ┆   ┆ ---   ┆ ---       ┆ s         ┆ itle      │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆   ┆ str   ┆ str       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ f64       ┆   ┆       ┆           ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════╪═══════════╪═══════════╪═══════════╡
│ B00MCW7G9M ┆ all electr ┆ FS-1051    ┆ 3.5       ┆ … ┆       ┆ fat shark ┆ electroni ┆ fs-1051   │
│            ┆ onics      ┆ FATSHARK   ┆           ┆   ┆       ┆           ┆ cs televi ┆ fatshark  │
│            ┆            ┆ TELEPORTER ┆           ┆   ┆       ┆           ┆ sion &    ┆ teleporte │
│            ┆            ┆ V3…        ┆           ┆   ┆       ┆           ┆ video…    ┆ r v3…     │
│ B00YT6XQSE ┆ all electr ┆ Ce-H22B12- ┆ 5.0       ┆ … ┆       ┆ siig      ┆ electroni ┆ ce-h22b12 │
│            ┆ onics      ┆ S1 4Kx2K   ┆           ┆   ┆       ┆           ┆ cs televi ┆ -s1 4kx2k │
│            ┆            ┆ Hdmi 4Port ┆           ┆   ┆       ┆           ┆ sion &    ┆ hdmi      │
│            ┆            ┆            ┆           ┆   ┆       ┆           ┆ video…    ┆ 4port     │
│ B07SM135LS ┆ computers  ┆ Digi-Tatoo ┆ 4.5       ┆ … ┆ 19.99 ┆ digi-tato ┆ electroni ┆ digi-tato │
│            ┆            ┆ Decal Skin ┆           ┆   ┆       ┆ o         ┆ cs        ┆ o decal   │
│            ┆            ┆ Compatib…  ┆           ┆   ┆       ┆           ┆ computers ┆ skin      │
│            ┆            ┆            ┆           ┆   ┆       ┆           ┆ & access… ┆ compatib… │
│ B089CNGZCW ┆ amazon     ┆ NotoCity   ┆ 4.5       ┆ … ┆ 9.99  ┆ notocity  ┆ electroni ┆ notocity  │
│            ┆ fashion    ┆ Compatible ┆           ┆   ┆       ┆           ┆ cs        ┆ compatibl │
│            ┆            ┆ with       ┆           ┆   ┆       ┆           ┆ wearable  ┆ e with    │
│            ┆            ┆ Vivoa…     ┆           ┆   ┆       ┆           ┆ technolog ┆ vivoa…    │
│            ┆            ┆            ┆           ┆   ┆       ┆           ┆ …         ┆           │
│ B004E2Z88O ┆ cell       ┆ Motorola   ┆ 3.8       ┆ … ┆ 14.99 ┆ verizon   ┆ electroni ┆ motorola  │
│            ┆ phones &   ┆ Droid X    ┆           ┆   ┆       ┆           ┆ cs        ┆ droid x   │
│            ┆ accessorie ┆ Essentials ┆           ┆   ┆       ┆           ┆ computers ┆ essential │
│            ┆ s          ┆ Co…        ┆           ┆   ┆       ┆           ┆ & access… ┆ s co…     │
└────────────┴────────────┴────────────┴───────────┴───┴───────┴───────────┴───────────┴───────────┘

In [9]:
# aggregate review titles so we return one grouped value containing joined review titltes to get one review title summary per row 
reviews_grouped =  reviews_clean.group_by("parent_asin").agg([
    pl.col("review_title")
        .drop_nulls()
        .str.join(" ")
        .alias("all_review_titles"),

    # count reviews for each prouduct 
    pl.len().alias("review_count"),

    # compute average rating 
    pl.col("rating").mean().alias("avg_rating")
])

# join the grouped review titles with the product metadata so we get one row per product for embeddingss 
retrieval_df = product_metadata_clean.join(
    reviews_grouped,
    on = "parent_asin",
    how = "left" # if a product has no reviews in the dataset, still include it
)

retrieval_df.head().collect()

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ parent_as ┆ main_cate ┆ title     ┆ average_r ┆ … ┆ product_t ┆ all_revie ┆ review_co ┆ avg_rati │
│ in        ┆ gory      ┆ ---       ┆ ating     ┆   ┆ itle      ┆ w_titles  ┆ unt       ┆ ng       │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆           ┆ f64       ┆   ┆ str       ┆ str       ┆ u32       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ B00MCW7G9 ┆ all elect ┆ FS-1051   ┆ 3.5       ┆ … ┆ fs-1051   ┆ recall,   ┆ 5         ┆ 3.6      │
│ M         ┆ ronics    ┆ FATSHARK  ┆           ┆   ┆ fatshark  ┆ recall,   ┆           ┆          │
│           ┆           ┆ TELEPORTE ┆           ┆   ┆ teleporte ┆ recall... ┆           ┆          │
│           ┆           ┆ R V3…     ┆           ┆   ┆ r v3…     ┆ .... …    ┆           ┆          │
│ B00YT6XQS ┆ all elect ┆ Ce-H22B12 ┆ 5.0       ┆ … ┆ ce-h22b12 ┆ does what ┆ 1         ┆ 5.0      │
│ E         ┆ ronics    ┆ -S1 4Kx2K ┆           ┆   ┆ -s1 4kx2k ┆ it’s      ┆           ┆          │
│           ┆           ┆ Hdmi      ┆           ┆   ┆ hdmi      ┆ supposed  ┆           ┆          │
│           ┆           ┆ 4Port     ┆           ┆   ┆ 4port     ┆ to, sp…   ┆           ┆          │
│ B07SM135L ┆ computers ┆ Digi-Tato ┆ 4.5       ┆ … ┆ digi-tato ┆ looks     ┆ 49        ┆ 4.408163 │
│ S         ┆           ┆ o Decal   ┆           ┆   ┆ o decal   ┆ nice and  ┆           ┆          │
│           ┆           ┆ Skin      ┆           ┆   ┆ skin      ┆ provides  ┆           ┆          │
│           ┆           ┆ Compatib… ┆           ┆   ┆ compatib… ┆ the pr…   ┆           ┆          │
│ B089CNGZC ┆ amazon    ┆ NotoCity  ┆ 4.5       ┆ … ┆ notocity  ┆ size is   ┆ 45        ┆ 4.377778 │
│ W         ┆ fashion   ┆ Compatibl ┆           ┆   ┆ compatibl ┆ good      ┆           ┆          │
│           ┆           ┆ e with    ┆           ┆   ┆ e with    ┆ great     ┆           ┆          │
│           ┆           ┆ Vivoa…    ┆           ┆   ┆ vivoa…    ┆ band for  ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ la…       ┆           ┆          │
│ B004E2Z88 ┆ cell      ┆ Motorola  ┆ 3.8       ┆ … ┆ motorola  ┆ great     ┆ 40        ┆ 4.65     │
│ O         ┆ phones &  ┆ Droid X   ┆           ┆   ┆ droid x   ┆ product,  ┆           ┆          │
│           ┆ accessori ┆ Essential ┆           ┆   ┆ essential ┆ great pur ┆           ┆          │
│           ┆ es        ┆ s Co…     ┆           ┆   ┆ s co…     ┆ chase,…   ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# make one retrieval text document per product with the product title, main category, store, deatures, description, categories, and review titles 
# Docs used for syntax help: https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.lit.html, https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.concat_str.html and https://stackoverflow.com/questions/72400218/how-to-use-polars-concat-str-to-combine-multiple-columns-selected-by-regex
retrieval_df = retrieval_df.with_columns([
    pl.concat_str([ 
        pl.lit("product title: "), pl.col("product_title").fill_null(""),
        pl.lit(". main category: "), pl.col("main_category").fill_null(""),
        pl.lit(". store: "), pl.col("store").fill_null(""),
        pl.lit(". features of product: "), pl.col("features").fill_null(""),
        pl.lit(". description: "), pl.col("description").fill_null(""),
        pl.lit(". categories: "), pl.col("categories").fill_null(""),
        pl.lit(". all review titles: "), pl.col("all_review_titles").fill_null("")
    ], separator = "")
    .str.replace_all(r"\s+", " ") # replace consecutive whitespace chars
    .str.strip_chars() # remove leading and trailing whitespace chars: https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.str.strip_chars.html
    .alias("retrieval_text")
])

# keep all useful columns that we mentioned above, including retrieval_text (column that will be used for embeddings) and metadata columns such as price
retrieval_corpus = retrieval_df.select([
    "parent_asin",
    "product_title",
    "description",
    "main_category",
    "store",
    "price",
    "average_rating",
    "rating_number",
    "review_count",
    "features",
    "categories",
    "all_review_titles",
    "retrieval_text"
])

retrieval_corpus.select(pl.len()).collect()


# write the lazy frame to a parquet file using sink_parquet(): https://docs.pola.rs/api/python/stable/reference/api/polars.LazyFrame.sink_parquet.html
retrieval_corpus.sink_parquet("../data/processed/retrieval_corpus.parquet")

In [11]:
from langchain_core.documents import Document

# ingest each retrieval text and metadata into a LangChain document. We used metadata to produce better user output and support more diverse user queries such as ones related to price.
# used the docs for help with metadata parsing: https://reference.langchain.com/python/langchain-core/documents/base/Document
documents = []
retrieval_corpus_df = retrieval_corpus.collect()

for row in retrieval_corpus_df.iter_rows(named = True):
    document = Document(
        page_content = row["retrieval_text"],
        metadata = {
            "parent_asin": row["parent_asin"],
            "product_title": row["product_title"],
            "main_category": row["main_category"],
            "description": row["description"],
            "store": row["store"],
            "price": row["price"],
            "average_rating": row["average_rating"],
            "rating_number": row["rating_number"],
            "review_count": row["review_count"],
        }
    )

    documents.append(document)

In [12]:
# confirm a few documents got loaded into the DocumentLoader
print(type(documents[0]))
print(documents[0])

<class 'langchain_core.documents.base.Document'>
page_content='product title: fs-1051 fatshark teleporter v3 headset. main category: all electronics. store: fat shark. features of product: . description: teleporter v3 the “teleporter v3” kit sets a new level of value in the fpv world with fat shark renowned performance and quality. the fun of fpv is experienced firsthand through the large screen fpv headset with integrated nexwaverf receiver technology while simultaneously recording onboard hd footage with the included “pilothd” camera. the “teleporter v3” kit comes complete with everything you need to step into the cockpit of your fpv vehicle. we’ve included our powerful 250mw 5.8ghz transmitter, 25 degree fov headset (largest qvga display available), the brand new “pilothd” camera with live av out and all the cables, antennas and connectors needed.. categories: electronics television & video video glasses. all review titles: recall, recall, recall....... easy to install ... go back and spend another $50 to get the better spend more on a better version or different brand fpv at a great price for the win!!' metadata={'parent_asin': 'B00MCW7G9M', 'product_title': 'fs-1051 fatshark teleporter v3 headset', 'main_category': 'all electronics', 'description': 'teleporter v3 the “teleporter v3” kit sets a new level of value in the fpv world with fat shark renowned performance and quality. the fun of fpv is experienced firsthand through the large screen fpv headset with integrated nexwaverf receiver technology while simultaneously recording onboard hd footage with the included “pilothd” camera. the “teleporter v3” kit comes complete with everything you need to step into the cockpit of your fpv vehicle. we’ve included our powerful 250mw 5.8ghz transmitter, 25 degree fov headset (largest qvga display available), the brand new “pilothd” camera with live av out and all the cables, antennas and connectors needed.', 'store': 'fat shark', 'price': '', 'average_rating': 3.5, 'rating_number': 6, 'review_count': 5}

In [13]:
# print out content vs metadata
print("PAGE CONTENT:\n", documents[0].page_content[:300])
print("\nMETADATA:\n", documents[0].metadata)

PAGE CONTENT:
 product title: fs-1051 fatshark teleporter v3 headset. main category: all electronics. store: fat shark. features of product: . description: teleporter v3 the “teleporter v3” kit sets a new level of value in the fpv world with fat shark renowned performance and quality. the fun of fpv is experienced

METADATA:
 {'parent_asin': 'B00MCW7G9M', 'product_title': 'fs-1051 fatshark teleporter v3 headset', 'main_category': 'all electronics', 'description': 'teleporter v3 the “teleporter v3” kit sets a new level of value in the fpv world with fat shark renowned performance and quality. the fun of fpv is experienced firsthand through the large screen fpv headset with integrated nexwaverf receiver technology while simultaneously recording onboard hd footage with the included “pilothd” camera. the “teleporter v3” kit comes complete with everything you need to step into the cockpit of your fpv vehicle. we’ve included our powerful 250mw 5.8ghz transmitter, 25 degree fov headset (largest qvga display available), the brand new “pilothd” camera with live av out and all the cables, antennas and connectors needed.', 'store': 'fat shark', 'price': '', 'average_rating': 3.5, 'rating_number': 6, 'review_count': 5}

In [14]:
# confirm the number of rows from the retrieval_corpus match the length of the documents
print("Number of documents:", len(documents))
print(retrieval_corpus.select(pl.len()).collect())

Number of documents: 1610012
shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 1610012 │
└─────────┘

In [15]:
# make sure the path we want to save the LangChain docs to exists
Path("../data/processed").mkdir(parents = True, exist_ok = True)

# persist the list of LangChain documents using pickle 
with open("../data/processed/langchain_documents.pkl", "wb") as f:
    pickle.dump(documents, f)